### ISSUE TITLE
Create Electron-based UI

### ISSUE THREAD

**Issue by holiman** [holiman/Cleftron#1]
`Clef` was integrated into Geth the other day.

## Background

Main docs is here:
https://github.com/ethereum/go-ethereum/tree/master/cmd/clef

Tutorial:
https://github.com/ethereum/go-ethereum/blob/master/cmd/clef/tutorial.md

Docs about rules:
https://github.com/ethereum/go-ethereum/blob/master/cmd/clef/rules.md

There exists a QT-based UI here: https://github.com/holiman/qtsigner. The QT-based UI is somewhat full-fledged, in that it supports modifying requests in the UI (not just approve/deny). 

There is also a GTK-based UI: https://github.com/holiman/gtksigner (very much work in
progress, I wrote it to be able to run on Qubes-os on a Fedora-based Qube). This is much less advanced. 

### Task

Create a small Electron-based UI, fully bundled with no external components, which starts `clef` under the hood and communicates with the binary process. 

For starters, a minimal UI which can only approve/deny operations is sufficient. The UI should, like the QT-based one, have a system tray icon which is activated when requests come in. The user should be able to click it, see  the provided information about the request, and approve/deny the operation. 

The entire thing should be bundled, and not depend on loading external resources. It should not require having nodejs or npm libraries installed.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 7000.00
Contract address: [0x1b421da427839f5cc998c290793f070d4591c5fe](https://etherscan.io/address/0x1b421da427839f5cc998c290793f070d4591c5fe)
Network: Mainnet
Paid to: StevenJNPearce
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by kenshyx** [comment]
How it should handle the version updates for `clef`? By having it bundled inside the electron app it would require to release a new version of `cleftron` every time.

**Comment by holiman** [comment]
It should do like the QT ui does: take binary as an argument. It should also verify the permissions, and inform the user about the sha256hash for the binary.

Also, if it detects that the signers api version number is incompatible, it should inform and possibly exit.

**Comment by holiman** [comment]
Clef will tell the UI the semver of the api

**Comment by holiman** [comment]
So, sorry for confusion. I meant no external dependecies like libraries or UI resources. But it should not bundle clef.

**Comment by StevenJNPearce** [comment]
I am starting work on this.

**Comment by StevenJNPearce** [comment]
Are you on slack/discord somewhere? I have a couple of questions and a bug report for Clef itself.

stevenjnpearce@gmail.com

**Comment by georgiemathews** [comment]
@StevenJNPearce @holiman, I already started working on this a day ago. What's the best way of going about this?

**Comment by StevenJNPearce** [comment]
@georgiemathews I hope not too much work has been replicated. I'm currently around the level of functionality of the Qt-based UI. I will get the code in a state such that is ready for us to coordinate/collaborate and upload it on github ASAP.

**Comment by StevenJNPearce** [comment]
https://github.com/StevenJNPearce/Cleftron

Nearly done, just needs a little polish. i will make a pull request tomorrow.

**Comment by holiman** [comment]
Sorry I didn't answe until now. Hope you/we can sort out the bounty/work to everyone's satisfaction. 

There's a gitter room ethereum/signer to ask questions, also martin.swende at ethereum.org

**Comment by StevenJNPearce** [comment]
Here it is:  #2 

Some notes:
1) Clef fails on windows. checkFile only checks for Unix permissions. [https://github.com/ethereum/go-ethereum/blob/784aa83942e3dbc9bab0385475dbf3755a9892ac/cmd/clef/main.go#L544](url)

2) `ApproveNewAccount` and `ApproveImport` are not documented with the other methods here: [https://github.com/ethereum/go-ethereum/blame/master/cmd/clef/README.md#L535](url). I've implemented them in this UI, but you will need to check the functionality is correct.

3) travis.yml and appveyor.yml files included for easy CI/building.

**Comment by georgiemathews** [comment]
@StevenJNPearce why the decision to use Vue?

**Comment by StevenJNPearce** [comment]
Well, just personal preference. In Vue I can finish work easier and more quickly than with React.

**Comment by holiman** [comment]
Thank you @StevenJNPearce . As I'm no electron-guru, I'll get some more eyes on the PR from people who are better at it than me.
 
Two questions:

1. What is the easiest way for me to run this on some debian-machine (in dev-mode, so assuming I have npm or whatever is needed)?
2. What is the process for building it into standalone binaries/packages for distribution/release?

**Comment by StevenJNPearce** [comment]
@holiman 

1) `npm install` and then `npm run dev`

2) `npm run build` for quick build. TravisCI(macOS/Linux) + Appveyor(windows) for automated build/release, check "Automated deployments using CI" section here: [https://simulatedgreg.gitbooks.io/electron-vue/content/en/using-electron-builder.html](url)
